### ISSUE TITLE
[1.4.6] Incorrect behaviour with noseeds and ignore-seeds

### ISSUE THREAD

**Issue by sarhatabaot** [sarhatabaot/FarmAssistReboot#102]
When ignore seeds is enabled, the plugin will not work properly unless `farmassist.noseeds` is added as a permission.

**Comment by tncc2k** [comment]
At first I thought "farmassist.noseeds" was the problem. But no after reviewing I found "ignore-seeds" was the main problem.
And 1 more problem with 1.4.6, when I break TORCHFLOWER in the console it will show error. Version 1.4.5 does not
Now I'm using ver 1.4.5 everything works fine with "ignore-seeds" false

[01:29:46 ERROR]: Could not pass event BlockBreakEvent to FarmAssistReboot v1.4.6
java.lang.IllegalArgumentException: No enum constant com.github.sarhatabaot.farmassistreboot.Crop.TORCHFLOWER at java.base/java.lang.Enum.valueOf(Enum.java:293) ~[?:?]
at FarmAssistReboot-1.4.6.jar/com.github.sarhatabaot.farmassistreboot.Crop.valueOf(Crop.java:12) ~[FarmAssistReboot-1.4.6.jar:?]
at FarmAssistReboot-1.4.6.jar/com.github.sarhatabaot.farmassistreboot.Util.inventoryContainsSeeds(Util.java:46) ~[FarmAssistReboot-1.4.6.jar:?]
