### ISSUE TITLE
beetrootseed not auto replant

### ISSUE THREAD

**Issue by steven11304** [sarhatabaot/FarmAssistReboot#17]
the other crops are all working 
but only beetrootseed not auto replant

**Comment by steven11304** [comment]
i have op permission so it is not a permission issue

**Comment by steven11304** [comment]
[11:31:17 ERROR]: Could not pass event BlockBreakEvent to FarmAssistReboot v1.1.0
java.lang.IllegalArgumentException: No enum constant com.github.sarhatabaot.farmassistreboot.Crop.BEETROOTS
at java.lang.Enum.valueOf(Enum.java:240) ~[?:?]
at com.github.sarhatabaot.farmassistreboot.Crop.valueOf(Crop.java:6) ~[?:?]
at com.github.sarhatabaot.farmassistreboot.Util.replant(Util.java:55) ~[?:?]
at com.github.sarhatabaot.farmassistreboot.listeners.BlockBreakListener.applyReplant(BlockBreakListener.java:89) ~[?:?]
at com.github.sarhatabaot.farmassistreboot.listeners.BlockBreakListener.onBlockBreak(BlockBreakListener.java:56) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1291.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[ssspigot8994594172551164463.jar:SSSpigot-1.16.5-20210409-3c3b2cc]
at org.bukkit.plugin.EventExecutor$$Lambda$4886/000000002E57A7E0.execute(Unknown Source) ~[?:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[ssspigot8994594172551164463.jar:SSSpigot-1.16.5-20210409-3c3b2cc]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[ssspigot8994594172551164463.jar:SSSpigot-1.16.5-20210409-3c3b2cc]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:622) ~[ssspigot8994594172551164463.jar:SSSpigot-1.16.5-20210409-3c3b2cc]
at net.minecraft.server.v1_16_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:390) ~[ssspigot8994594172551164463.jar:SSSpigot-1.16.5-20210409-3c3b2cc]
at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:343) ~[ssspigot8994594172551164463.jar:SSSpigot-1.16.5-20210409-3c3b2cc]
at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:278) ~[ssspigot8994594172551164463.jar:SSSpigot-1.16.5-20210409-3c3b2cc]
at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1730) ~[ssspigot8994594172551164463.jar:SSSpigot-1.16.5-20210409-3c3b2cc]
at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:32) ~[ssspigot8994594172551164463.jar:SSSpigot-1.16.5-20210409-3c3b2cc]
at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:9) ~[ssspigot8994594172551164463.jar:SSSpigot-1.16.5-20210409-3c3b2cc]
at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:53) ~[ssspigot8994594172551164463.jar:SSSpigot-1.16.5-20210409-3c3b2cc]
at net.minecraft.server.v1_16_R3.PlayerConnectionUtils$$Lambda$7558/000000000D18B060.run(Unknown Source) ~[?:?]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:151) ~[ssspigot8994594172551164463.jar:SSSpigot-1.16.5-20210409-3c3b2cc]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[ssspigot8994594172551164463.jar:SSSpigot-1.16.5-20210409-3c3b2cc]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:113) ~[ssspigot8994594172551164463.jar:SSSpigot-1.16.5-20210409-3c3b2cc]
at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1331) ~[ssspigot8994594172551164463.jar:SSSpigot-1.16.5-20210409-3c3b2cc]
at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1324) ~[ssspigot8994594172551164463.jar:SSSpigot-1.16.5-20210409-3c3b2cc]
at net.minecraft.server.v1_16_R3.TickServ.endOfTick(TickServ.java:204) ~[ssspigot8994594172551164463.jar:SSSpigot-1.16.5-20210409-3c3b2cc]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1483) ~[ssspigot8994594172551164463.jar:SSSpigot-1.16.5-20210409-3c3b2cc]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1120) ~[ssspigot8994594172551164463.jar:SSSpigot-1.16.5-20210409-3c3b2cc]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[ssspigot8994594172551164463.jar:SSSpigot-1.16.5-20210409-3c3b2cc]
at net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3077/0000000035A3B1D0.run(Unknown Source) ~[?:?]
at java.lang.Thread.run(Thread.java:836) [?:?]

**Comment by sarhatabaot** [comment]
Fixed in d8b9f51c40b75b7318d09d708d50e174164f3751
