### ISSUE TITLE
No supporting for Folia!

### ISSUE THREAD

**Issue by Tibarica** [sarhatabaot/FarmAssistReboot#93]
[18:44:11 ERROR]: [DirectoryProviderSource] Error loading plugin: Could not load plugin 'FarmAssistReboot v1.4.6' as it is not marked as supporting Folia!
java.lang.RuntimeException: Could not load plugin 'FarmAssistReboot v1.4.6' as it is not marked as supporting Folia!
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProviderFactory.build(SpigotPluginProviderFactory.java:40) ~[folia-1.21.1.jar:1.21.1-DEV-11e6f61]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProviderFactory.build(SpigotPluginProviderFactory.java:28) ~[folia-1.21.1.jar:1.21.1-DEV-11e6f61]
        at io.papermc.paper.plugin.provider.type.PluginFileType.register(PluginFileType.java:72) ~[folia-1.21.1.jar:1.21.1-DEV-11e6f61]
        at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:96) ~[folia-1.21.1.jar:1.21.1-DEV-11e6f61]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:52) ~[folia-1.21.1.jar:1.21.1-DEV-11e6f61]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:17) ~[folia-1.21.1.jar:1.21.1-DEV-11e6f61]
        at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:15) ~[folia-1.21.1.jar:1.21.1-DEV-11e6f61]
        at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:113) ~[folia-1.21.1.jar:1.21.1-DEV-11e6f61]
        at net.minecraft.server.Main.main(Main.java:123) ~[folia-1.21.1.jar:1.21.1-DEV-11e6f61]
        at io.papermc.paper.PaperBootstrap.boot(PaperBootstrap.java:21) ~[folia-1.21.1.jar:1.21.1-DEV-11e6f61]
        at org.bukkit.craftbukkit.Main.main(Main.java:281) ~[folia-1.21.1.jar:1.21.1-DEV-11e6f61]
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by maher-nakesh** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by sarhatabaot** [comment]
Hey! This will be coming with version 2.0.0 :)

**Comment by sarhatabaot** [comment]
This will be fully supported in 2.0.0, but also partially supported starting with 1.4.7, enjoy :)
